version: "3"
services:
  
  db:
    image: postgres:16.4
    ports:
      - 5432:5432
    volumes:
      - db-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
volumes:
  db-storage:
