openapi: 3.0.0
info:
  title: QRコードスタンプラリーアプリケーション
  description: QRコードスタンプラリーアプリケーションのAPI仕様書
  version: '0.1'
servers:
  - url: http://localhost:5173/api
    description: ローカル開発環境

tags:
  - name: User
    description: ユーザーに関する操作
  - name: Rally
    description: スタンプラリーに関する操作
  - name: Stamp
    description: スタンプに関する操作

paths:
  /users:
    get:
      summary: ユーザー一覧を取得する
      tags:
        - User
      operationId: get-users
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: '#/components/schemas/userSchema'
        '400':
          description: 失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    post:
      summary: ユーザーを登録する
      tags:
        - User
      operationId: post-user-register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                rally_id:
                  type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/userSchema'
        '400':
          description: 失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /users/{user_id}:
    get:
      summary: ユーザーを取得する
      tags:
        - User
      operationId: get-user
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/userSchema'
        '400':
          description: 失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    delete:
      summary: ユーザーを削除する
      tags:
        - User
      operationId: delete-user
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: 失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /users{user_id}/stamps:
    get:
      summary: ユーザーのスタンプ一覧を取得する
      tags:
        - User
      operationId: get-user-stamps
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/stampSchema'
        '400':
          description: 失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /rallies:
    get:
      summary: スタンプラリー一覧を取得する
      tags:
        - Rally
      operationId: get-rallies
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/rallySchema'
        '400':
          description: 失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    post:
      summary: スタンプラリーを作成する
      tags:
        - Rally
      operationId: post-rally
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/rallySchema'
        '400':
          description: 失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /rallies/{rally_id}:
    get:
      summary: スタンプラリーを取得する
      tags:
        - Rally
      operationId: get-rally
      parameters:
        - name: rally_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rallySchemaWithStamps'
    delete:
      summary: スタンプラリーを削除する
      tags:
        - Rally
      operationId: delete-rally
      parameters:
        - name: rally_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: 失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /rallies/{rally_id}/stamps:
    get:
      summary: スタンプラリーのスタンプ一覧を取得する
      tags:
        - Rally
      operationId: get-rally-stamps
      parameters:
        - name: rally_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/stampSchema'
    post:
      summary: スタンプラリーにスタンプを追加する
      tags:
        - Rally
      operationId: post-rally-stamp
      parameters:
        - name: rally_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                qr_code:
                  type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  stamp:
                    $ref: '#/components/schemas/stampSchema'
  
  /stamp/{stamp_id}:
    put:
      summary: スタンプを更新する
      tags:
        - Stamp
      operationId: put-stamp
      parameters:
        - name: stamp_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                qr_code:
                  type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/stampSchema'
    delete:
      summary: スタンプを削除する
      tags:
        - Stamp
      operationId: delete-stamp
      parameters:
        - name: stamp_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /stamp/{stamp_id}/collect/{user_id}:
    post:
      summary: スタンプを読み込む
      tags:
        - Stamp
      operationId: post-stamp-collect
      parameters:
        - name: stamp_id
          in: path
          required: true
          schema:
            type: string
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
            description: 成功
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
        '400':
          description: 失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    rallySchema:
      type: object
      properties:
        Id:
          type: string
        name:
          type: string
        description:
          type: string
        CreatedAt:
          type: string
        UpdatedAt:
          type: string
    stampSchema:
      type: object
      properties:
        Id:
          type: string
        name:
          type: string
        description:
          type: string
        qr_code:
          type: string
        CreatedAt:
          type: string
        UpdatedAt:
          type: string
    rallySchemaWithStamps:
      allOf:
        - $ref: '#/components/schemas/rallySchema'
        - type: object
          properties:
            stamps:
              type: array
              items:
                $ref: '#/components/schemas/stampSchema'
    userSchema:
      type: object
      properties:
        Id:
          type: string
        name:
          type: string
        rally_id:
          type: string
        CreatedAt:
          type: string
        UpdatedAt:
          type: string 